TERM=xterm-256color

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.dotfiles/zsh/oh-my-zsh

# zsh tmux settings
ZSH_TMUX_AUTOSTART='true'

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Setup options for agnoster theme
VIRTUAL_ENV_DISABLE_PROMPT=1
DEFAULT_USER=`whoami`
SOLARIZED_THEME="light"
ZSH_THEME="agnoster"


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux zsh-autosuggestions zsh-syntax-highlighting)

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin"
## Load custom plugins
source $ZSH/oh-my-zsh.sh

# Setup plugins configs
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=248'

# Setup colors
DIRCOLOR_BIN=gdircolors
if [[ `uname` = "Linux" ]]; then
  DIRCOLOR_BIN=dircolors
fi

eval `$DIRCOLOR_BIN $HOME/.dir_colors/dircolors.ansi-light`
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
unalias ls
if ls --color -d . >/dev/null 2>&1; then
  alias ls='ls --color=auto -F'
elif ls -G -d . >/dev/null 2>&1; then
  alias ls='gls --color=auto -F'   # use GNU coreutils ls
fi
alias ll='ls -lh'
alias la='ls -lAFh'
alias tree='tree -CF'
if [[ `uname` = Darwin ]]; then
  alias sb='reattach-to-user-namespace subl' # enable subl inside tmux
else
  alias sb=subl
fi
alias egrep='egrep --color=always'  # show colors when piping to less
alias grep='egrep'
alias ql='qlmanage -p "$@" > /dev/null 2>&1'
alias ip='ifconfig | colout "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"'

### Functions
function sms() {
  # Using tmobile provider. For a more elaborate list, check lib/carries.js in
  # https://github.com/typpo/textbelt
  provider=tmomail.net

  if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <phone number>"
  fi
  # TODO: check that it's a valid phone number
  mail -s "txt" $1@$provider
}


# Delete to beginning of line
bindkey \^U backward-kill-line
# Delete next word
bindkey \^D kill-word


### Add to PATH
export PATH=$PATH:/Library/TeX/texbin
export PATH=/usr/local/opt/python/libexec/bin:$PATH


### Increase maximum size of history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE


### Virtualenvwrapper things
VIRTUALENVWRAPPER_PYTHON="$(command \which python3)"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
if [ -f /usr/loca/bin/virtualenvwrapper.sh ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi

## Switch Capslock with Esc (TODO: check if works in Mac)
if [[ `uname` = Linux ]]; then
  xmodmap -e "remove Lock = Caps_Lock"
  xmodmap -e "remove Lock = Escape"
  xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
  xmodmap -e "keycode 66 = Escape NoSymbol Escape"
  xmodmap -e "keycode 108 = Return"
fi

## Alias for open files/explorer etc
if [[ `uname` = Linux ]]; then
  alias open="xdg-open"
fi


export HISTTIMEFORMAT="%d/%m/%y %T "

export PATH=/usr/local/texlive/2018/bin/x86_64-linux:$PATH
export PATH=$HOME/.local/bin:$PATH


# Homebrew doesn't properly link ruby package because of default macOS ruby
export PATH="/usr/local/opt/ruby/bin:$PATH"

alias xclip='xclip -sel clip'

# Alert 
alias alert="osascript -e 'tell application (path to frontmost application as text) to display dialog \"Done\" buttons {\"OK\"} with icon stop'"

# Automatically update command
function refresh() {
CMD="$@"
TIME=`date +%s`
CACHE_FILE=/tmp/`echo "$CMD_$TIME" | sed 's/ /_/g'`
clear
eval "$CMD"
while true; do
  sleep 1
  # Save current output
  eval "$CMD" &> "${CACHE_FILE}.new"

  # # Update if output different than cache
  if ! diff "$CACHE_FILE" "${CACHE_FILE}.new" &> /dev/null; then
    clear
    cp "${CACHE_FILE}.new" "$CACHE_FILE"
    eval "$CMD"  # Instead of `cat` for colorized output
  fi
done
}

# Automatically update git tr
alias gitr="refresh git --no-pager tr -20"
